// String searchValue = '';
// List state = [
//   "Andaman & Nicobar",
//   "Bihar",
//   "Dadra & Nagar Haveli",
//   "Gujarat",
//   "Andhar Pradesh",
//   "Chandigarh",
//   "Puducherry",
//   "west Bengal",
//   "Tripura",
//   "Himachal Pradesh",
//   "Rajasthan",
//   "Asam",
//   "New Delhi",
//   "Panjab",
//   "Jharkhand",
//   "Uttar Pradesh",
//   "Karnataka",
//   "Nagaland",
//   "Goa",
//   "Uttarakhand",
//   "Daman & Diu",
//   "Maharashtra",
// ];
//
// // {name:"Andaman & Nicobar"},
// // {name:"Bihar"},
// // {name:"Dadra & Nagar Haveli"},
// // {name:"Gujarat"},
// // {name:"Andhar Pradesh"},
// // {name:"Chandigarh"},
// // {name:"Puducherry"},
// // {name:"west Bengal"},
// // {name:"Tripura"},
// // {name:"Himachal Pradesh"},
// // {name:"Rajasthan"},
// // {name:"Asam"},
// // {name:"New Delhi"},
// // {name:"Panjab"},
// // {name:"Jharkhand"},
// // {name:"Uttar Pradesh"},
// // {name:"Karnataka"},
// // {name:"Nagaland"},
// // {name:"Goa"},
// // name:{"Uttarakhand"},
// // {name:"Daman & Diu"},
// // {name:"Maharashtra"},
